### ISSUE TITLE
Trusty crashes when a users does not have permissions

### ISSUE THREAD

**Issue by d-lamers** [pingpong-labs/trusty#10]
It seems that Trusty crashes when a user does not have any permission set

in_array() expects parameter 2 to be array, null given

On:

public function can($permission)
	{
		return in_array($permission, $this->permissions());
	}

A suggested fix would be:

public function can($permission)
	{
		return $this->permissions ? in_array($permission, $this->permissions) : false;
	}

**Comment by d-lamers** [comment]
Bumping this, please fix this because it's just such an easy fix and I don't want to fork it for something this small of a change

**Comment by maurocasas** [comment]
Wuss

**Comment by gravitano** [comment]
I've been fixed this a few days ago. I forgot specify the issue in the commit message. Update your package to the latest version. Thank you :)
